version: "3.8"

services:
  backend:
    container_name: NetmiPython
    build:
      context: ../netmi_backend/
      dockerfile: ../netmi_docker/netmi_backend/Dockerfile
    restart: unless-stopped
    networks:
      - netmi_net
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT_MODE=development
    volumes:
      - ${PWD}/../netmi_backend/src:/app/src
    env_file:
      - ./.env

  frontend:
    container_name: netmi_frontend
    build:
      context: ../netmi_frontend/
      dockerfile: ../netmi_docker/netmi_frontend/Dockerfile
    restart: always
    networks:
      - netmi_net
    ports:
      - "4200:80"
    env_file:
      - ./.env
    depends_on:
      - backend

networks:
  netmi_net:
    driver: bridge
